# Generated by Django 4.1.2 on 2022-10-31 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('is_admin', 'Is Deparment Admin'),)},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
