# Generated by Django 4.1.2 on 2022-10-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFactSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_ID', models.CharField(choices=[('O-01', 'O-01'), ('O-02', 'O-02'), ('O-03', 'O-03'), ('O-06', 'O-06'), ('O-07', 'O-07'), ('O-38', 'O-38'), ('O-40', 'O-40'), ('O-08', 'O-08'), ('O-09', 'O-09'), ('O-11', 'O-11'), ('O-13', 'O-13'), ('O-16', 'O-16'), ('O-20', 'O-20'), ('O-30', 'O-30'), ('O-33', 'O-33'), ('K-14', 'K-14'), ('K-03', 'K-03'), ('K-05', 'K-05'), ('K-07', 'K-07'), ('K-08', 'K-08'), ('K-13', 'K-13'), ('H-01', 'H-01'), ('H-06', 'H-06'), ('M-06', 'M-06')], max_length=5)),
                ('project_Phase', models.CharField(choices=[('Pre-Planning', 'Pre-Planning'), ('Planning', 'Planning'), ('Design', 'Design'), ('Plan/Design', 'Plan/Design'), ('Completed', 'Completed'), ('Plan/Design', 'EA/Design'), ('Construction', 'Construction'), ('Des/Constr', 'Des/Constr'), ('Plan/Des/Constr', 'Plan/Des/Constr')], max_length=50)),
                ('source_of_Funding', models.CharField(choices=[('General Fund', 'General Fund'), ('Special Fund', 'Special Fund'), ('GO Bonds', 'GO Bonds'), ('GO Bonds Repaid', 'GO Bonds Repaid'), ('Revenue Bonds', 'Revenue Bonds'), ('FED & Interstate', 'FED & Interstate'), ('FED & Primary', 'FED & Primary'), ('FED & Secondary', 'FED & Secondary'), ('FED & Urban', 'FED & Urban'), ('Other FED Funds', 'Other FED Funds'), ('FED Revenue Sharing', 'FED Revenue Sharing'), ('Private Contributions', 'Private Contributions'), ('County Funds', 'County Funds'), ('Trust Funds', 'Trust Funds'), ('Interdept Transfer', 'Interdept Transfer'), ('Revolving Fund', 'Revolving Fund'), ('Other Funds', 'Other Funds')], max_length=50)),
                ('funding_Received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('year_Funding_Received', models.IntegerField()),
                ('project_Status_Update', models.TextField()),
                ('links_report_studies', models.URLField(max_length=250)),
                ('links_images', models.FileField(upload_to='linkImages/')),
                ('inputPOC_lastname', models.CharField(max_length=100)),
                ('inputPOC_firstname', models.CharField(max_length=100)),
                ('inputPOC_email', models.EmailField(max_length=254)),
                ('inputDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
