# Generated by Django 4.1.2 on 2022-10-31 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectfactsheet',
            old_name='inputDate',
            new_name='input_Date',
        ),
        migrations.RenameField(
            model_name='projectfactsheet',
            old_name='inputPOC_email',
            new_name='input_POC_Email',
        ),
        migrations.RenameField(
            model_name='projectfactsheet',
            old_name='inputPOC_firstname',
            new_name='input_POC_First_Name',
        ),
        migrations.RenameField(
            model_name='projectfactsheet',
            old_name='inputPOC_lastname',
            new_name='input_POC_Last_Name',
        ),
        migrations.RenameField(
            model_name='projectfactsheet',
            old_name='links_images',
            new_name='links_Images',
        ),
        migrations.RenameField(
            model_name='projectfactsheet',
            old_name='links_report_studies',
            new_name='links_Report_Studies',
        ),
        migrations.RemoveField(
            model_name='projectfactsheet',
            name='id',
        ),
        migrations.AlterField(
            model_name='projectfactsheet',
            name='funding_Received',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='projectfactsheet',
            name='project_ID',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectfactsheet',
            name='year_Funding_Received',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
