# Generated by Django 4.1.2 on 2022-11-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0003_alter_projectfactsheet_links_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfactsheet',
            name='approved_by_staff',
            field=models.BooleanField(default=False),
        ),
    ]
