# Generated by Django 4.1.2 on 2022-11-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0004_projectfactsheet_approved_by_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfactsheet',
            name='rejected_by_staff',
            field=models.BooleanField(default=False),
        ),
    ]
