# Generated by Django 4.1.2 on 2022-12-04 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('input', '0005_projectfactsheet_rejected_by_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfactsheet',
            name='input_POC_User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
